apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: url
  name: url
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: url
    spec:
      containers:
      - image: sivvaundavalli/metrics:version3
        name: metrics
        resources: {}
